# Generated by Django 5.2 on 2025-04-22 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('brnumb', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('brname', models.CharField(max_length=25)),
                ('brlocation', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'BRANCH',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('employname', models.CharField(blank=True, max_length=40, null=True)),
                ('deptname', models.CharField(blank=True, max_length=25, null=True)),
                ('brnumb', models.ForeignKey(db_column='BRNUMB', on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingsystem.branch')),
            ],
            options={
                'db_table': 'EMPLOYEE',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('ticname', models.CharField(blank=True, max_length=100, null=True)),
                ('ticcreatedate', models.DateTimeField()),
                ('ticacceptdate', models.DateTimeField(blank=True, null=True)),
                ('ticpriority', models.CharField(blank=True, max_length=10, null=True)),
                ('ticclosetime', models.DateTimeField(blank=True, null=True)),
                ('agentid', models.ForeignKey(db_column='AGENTID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_handled', to='ticketingsystem.employee')),
                ('employid', models.ForeignKey(db_column='EMPLOYID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets_submitted', to='ticketingsystem.employee')),
            ],
            options={
                'db_table': 'TICKET',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('agentid', models.ForeignKey(blank=True, db_column='AGENTID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_as_agent', to='ticketingsystem.employee')),
                ('employid', models.ForeignKey(blank=True, db_column='EMPLOYID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_as_employee', to='ticketingsystem.employee')),
                ('ticid', models.ForeignKey(db_column='TICID', on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingsystem.ticket')),
            ],
            options={
                'db_table': 'COMMENT',
                'unique_together': {('commentid', 'ticid')},
            },
        ),
        migrations.CreateModel(
            name='Ticketmetrics',
            fields=[
                ('ticclosetime', models.DateTimeField(primary_key=True, serialize=False)),
                ('satisfaction', models.CharField(max_length=1)),
                ('agentid', models.ForeignKey(db_column='AGENTID', on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingsystem.employee')),
                ('ticid', models.OneToOneField(db_column='TICID', on_delete=django.db.models.deletion.DO_NOTHING, to='ticketingsystem.ticket')),
            ],
            options={
                'db_table': 'TICKETMETRICS',
                'unique_together': {('ticclosetime', 'ticid')},
            },
        ),
    ]
